/**
 * The lattice. `meet`, `isNarrowerThan` and `permits` are checked against cases
 * generated by the Python library, so the two agree on every wire form — and
 * the core invariant (a child can never exceed its parent) is asserted directly.
 */

import assert from "node:assert/strict";
import test from "node:test";

import { Authority } from "../src/authority.js";
import {
  Allow,
  CallLimit,
  Deny,
  EgressRank,
  Prefix,
  RowLimit,
  SpendCap,
  UnknownCeiling,
  ceilingFromWire,
} from "../src/ceilings.js";
import { canonicalJson } from "../src/canonical.js";
import { ReasonCode } from "../src/reasons.js";
import { fixtureJson } from "./helpers.js";

interface DelegationCase {
  name: string;
  parent: any;
  request: any;
  expected_child: any;
  child_narrower_than_parent: boolean;
}

interface SubsumptionCase {
  name: string;
  a: any;
  b: any;
  expected: boolean;
}

interface PermitsCase {
  name: string;
  authority: any;
  scope: string;
  context: Record<string, any>;
  expected: { allowed: boolean; codes: string[] };
}

const delegationCases = fixtureJson<DelegationCase[]>("delegation_cases.json");
const subsumptionCases = fixtureJson<SubsumptionCase[]>("subsumption_cases.json");
const permitsCases = fixtureJson<PermitsCase[]>("permits_cases.json");

test("meet produces the same child authority as Python, in wire form", () => {
  assert.ok(delegationCases.length > 0);
  for (const c of delegationCases) {
    const parent = Authority.fromWire(c.parent);
    const request = Authority.fromWire(c.request);
    const child = parent.meet(request);
    assert.equal(canonicalJson(child.toWire() as any), canonicalJson(c.expected_child), c.name);
    assert.equal(child.isNarrowerThan(parent), c.child_narrower_than_parent, c.name);
  }
});

test("the child of a meet is never wider than the parent — the core invariant", () => {
  for (const c of delegationCases) {
    const parent = Authority.fromWire(c.parent);
    const child = parent.meet(Authority.fromWire(c.request));
    assert.ok(child.isNarrowerThan(parent), `${c.name}: child must be within the parent`);
  }
});

test("meet is commutative", () => {
  // One exception, faithfully inherited from the Python implementation: when two
  // prefix bounds are incomparable, neither is a prefix of the other, so no real
  // value can satisfy both. Both orders encode that as a bound admitting nothing,
  // but the encoding records the operands in the order it saw them. The admitted
  // set is identical — which is what soundness rests on — and the case below
  // checks that directly.
  const encodingIsOrderDependent = new Set(["membership meet incomparable_prefix"]);
  for (const c of delegationCases) {
    if (encodingIsOrderDependent.has(c.name)) continue;
    const a = Authority.fromWire(c.parent);
    const b = Authority.fromWire(c.request);
    assert.equal(
      canonicalJson(a.meet(b).toWire() as any),
      canonicalJson(b.meet(a).toWire() as any),
      c.name,
    );
  }
});

test("an incomparable-prefix meet admits nothing, whichever order it is taken in", () => {
  const c = delegationCases.find((x) => x.name === "membership meet incomparable_prefix")!;
  const a = Authority.fromWire(c.parent);
  const b = Authority.fromWire(c.request);
  for (const child of [a.meet(b), b.meet(a)]) {
    assert.deepEqual([...child.scopes], [...a.meet(b).scopes]);
    assert.equal(child.ttl, a.meet(b).ttl);
    for (const path of ["/srv/data/x", "/var/log/x", "/", ""]) {
      assert.equal(child.permits("db.query", { path }).allowed, false, path);
    }
  }
});

test("isNarrowerThan agrees with Python on every pair", () => {
  assert.ok(subsumptionCases.length > 0);
  for (const c of subsumptionCases) {
    const a = Authority.fromWire(c.a);
    const b = Authority.fromWire(c.b);
    assert.equal(a.isNarrowerThan(b), c.expected, c.name);
  }
});

test("permits agrees with Python on outcome and reason codes", () => {
  assert.ok(permitsCases.length > 0);
  for (const c of permitsCases) {
    const decision = Authority.fromWire(c.authority).permits(c.scope, c.context);
    assert.equal(decision.allowed, c.expected.allowed, c.name);
    const codes = decision.reasons.map((r) => r.code).sort();
    assert.deepEqual(codes, c.expected.codes, c.name);
  }
});

test("a request wider than the parent comes back narrowed, not refused", () => {
  const parent = new Authority({ scopes: ["crm.read"], ceilings: [new RowLimit(100)], ttl: 60 });
  const child = parent.meet(
    new Authority({ scopes: ["crm.read", "crm.delete"], ceilings: [new RowLimit(10_000)], ttl: 9999 }),
  );
  assert.deepEqual([...child.scopes], ["crm.read"]);
  assert.equal((child.ceiling("max_rows") as RowLimit).maxRows, 100);
  assert.equal(child.ttl, 60);
});

test("a wildcard covers its family but not the reverse", () => {
  const wide = new Authority({ scopes: ["crm.*"] });
  assert.ok(wide.coversScope("crm.read"));
  assert.ok(wide.coversScope("crm.write"));
  assert.ok(!wide.coversScope("mail.send"));
  assert.ok(!new Authority({ scopes: ["crm.read"] }).coversScope("crm.write"));
  // A wildcard granted by both sides survives the meet rather than being pruned.
  const both = wide.meet(new Authority({ scopes: ["crm.*"] }));
  assert.deepEqual([...both.scopes], ["crm.*"]);
});

test("a ceiling only ever appears or tightens across a meet", () => {
  const parent = new Authority({ scopes: ["x"], ceilings: [new RowLimit(100)] });
  const request = new Authority({ scopes: ["x"], ceilings: [new SpendCap(5)] });
  const child = parent.meet(request);
  assert.equal((child.ceiling("max_rows") as RowLimit).maxRows, 100);
  assert.equal((child.ceiling("max_spend") as SpendCap).maxSpend, 5);
  assert.equal(child.ceilings.length, 2);
});

test("an unbounded dimension is more powerful, so it is not narrower", () => {
  const bounded = new Authority({ scopes: ["x"], ceilings: [new RowLimit(10)], ttl: 1 });
  const unbounded = new Authority({ scopes: ["x"], ttl: 1 });
  assert.ok(bounded.isNarrowerThan(unbounded));
  assert.ok(!unbounded.isNarrowerThan(bounded));
});

test("a null ttl is not narrower than a bounded one", () => {
  const forever = new Authority({ scopes: ["x"], ttl: null });
  const hour = new Authority({ scopes: ["x"], ttl: 3600 });
  assert.ok(hour.isNarrowerThan(forever));
  assert.ok(!forever.isNarrowerThan(hour));
});

test("an unrecognised constraint fails closed rather than going unenforced", () => {
  const c = ceilingFromWire({ key: "max_widgets", type: "widgets", max: 4 });
  assert.ok(c instanceof UnknownCeiling);
  const decision = c.permits({});
  assert.equal(decision.allowed, false);
  assert.equal(decision.reasons[0]!.code, ReasonCode.UNKNOWN_CONSTRAINT);
  // It survives a meet unchanged, so it can never resolve to something wider.
  assert.ok(c.narrow(new RowLimit(1)) instanceof UnknownCeiling);
  assert.equal(c.subsumes(new RowLimit(1)), false);
  assert.deepEqual(c.toWire(), { key: "max_widgets", type: "widgets", max: 4 });
});

test("incomparable prefixes meet to a bound that admits nothing", () => {
  const a = new Prefix("path", "/srv/");
  const b = new Prefix("path", "/var/");
  const met = a.narrow(b);
  assert.equal(met.permits({ path: "/srv/data" }).allowed, false);
  assert.equal(met.permits({ path: "/var/log" }).allowed, false);
  // A comparable pair keeps the more specific one.
  assert.equal((new Prefix("path", "/srv/").narrow(new Prefix("path", "/srv/data/"))).prefix, "/srv/data/");
});

test("membership ceilings narrow in the safe direction", () => {
  const allow = new Allow("region", ["eu", "us"]).narrow(new Allow("region", ["eu", "ap"]));
  assert.deepEqual((allow as Allow).toWire()["one_of"], ["eu"]);
  const deny = new Deny("table", ["a"]).narrow(new Deny("table", ["b"]));
  assert.deepEqual((deny as Deny).toWire()["not_one_of"], ["a", "b"]);
});

test("egress is an ordered rank, and an unknown value fails closed", () => {
  const internal = new EgressRank("internal");
  assert.ok(internal.permits({ egress: "none" }).allowed);
  assert.ok(internal.permits({ egress: "internal" }).allowed);
  assert.ok(!internal.permits({ egress: "any" }).allowed);
  assert.ok(!internal.permits({ egress: "somewhere-else" }).allowed);
  assert.equal((internal.narrow(new EgressRank("none")) as EgressRank).level, "none");
});

test("a scoped call limit is its own dimension", () => {
  const unscoped = new CallLimit(10);
  const scoped = new CallLimit(3, "web.fetch");
  assert.equal(unscoped.key, "max_calls");
  assert.equal(scoped.key, "max_calls[web.fetch]");
  assert.equal(scoped.ctxField, "calls[web.fetch]");
  assert.equal(scoped.meterKey, "web.fetch");
  assert.ok(scoped.appliesToScope("web.fetch"));
  assert.ok(!scoped.appliesToScope("web.search"));
  assert.ok(new CallLimit(3, "web.*").appliesToScope("web.search"));
  const auth = new Authority({ scopes: ["web.fetch"], ceilings: [unscoped, scoped] });
  assert.equal(auth.ceilings.length, 2);
});

test("a wire form round-trips through fromWire unchanged", () => {
  const auth = new Authority({
    scopes: ["crm.*", "mail.send"],
    ceilings: [new RowLimit(10), new EgressRank("none"), new Allow("region", ["eu"]), new CallLimit(2, "web.*")],
    ttl: 900,
  });
  const wire = auth.toWire();
  assert.equal(
    canonicalJson(Authority.fromWire(wire).toWire() as any),
    canonicalJson(wire as any),
  );
});

test("describe is stable and readable", () => {
  const auth = new Authority({ scopes: ["b", "a"], ceilings: [new RowLimit(5)], ttl: 60 });
  assert.equal(auth.describe(), "scopes=[a, b] ceilings=[max_rows<=5] ttl=60");
});
