/**
 * The Internet-Draft's offline verification algorithm, checked against the
 * interop vectors.
 *
 * `test/fixtures/vectors/` holds one Delegation Chain that MUST verify and seven
 * adversarial chains that MUST each be rejected — every one of them generated by
 * the Python reference implementation and carrying the reason it must be
 * rejected FOR. That last part is the point: a chain rejected for the wrong
 * reason is a verifier that happens to be right today, and these assertions fail
 * on it. The `signer` block in each file is a published HS256 secret, so the
 * vectors pin down the wire format and the algorithm, both of which are
 * signature-scheme-agnostic, rather than a production trust boundary.
 */

import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import { Authority } from "../src/authority.js";
import { canonicalJson } from "../src/canonical.js";
import { EgressRank, RowLimit } from "../src/ceilings.js";
import { ReasonCode } from "../src/reasons.js";
import { HS256TestSigner, WireError, WireReasonCode, load } from "../src/wire.js";
import { fixtureJson } from "./helpers.js";

interface Vector {
  description: string;
  signer: { alg: string; kid: string; secret_hex: string };
  now: number;
  tokens: string[];
  expect?: string;
  expect_reject_reason?: string;
}

const REJECT_VECTORS = [
  "reject_widened_scope",
  "reject_exceeded_ceiling",
  "reject_spliced_parent",
  "reject_depth_exceeded",
  "reject_nonmonotonic_exp",
  "reject_bad_signature",
  "reject_wildcard_widening",
];

function vector(name: string): Vector {
  return fixtureJson<Vector>(`vectors/${name}.json`);
}

function signerFor(v: Vector): HS256TestSigner {
  assert.equal(v.signer.alg, "HS256", "these vectors are HS256; the loader must be told so");
  return new HS256TestSigner(Buffer.from(v.signer.secret_hex, "hex"), v.signer.kid);
}

/** The reason `load` rejected `v`, or "accept" if it did not reject it. */
function outcome(v: Vector): string {
  try {
    load(v.tokens, signerFor(v), { now: v.now });
    return "accept";
  } catch (e) {
    assert.ok(e instanceof WireError, `expected a WireError, got ${String(e)}`);
    return e.reason;
  }
}

test("the valid 3-hop chain verifies, and yields the formatter's authority", () => {
  const v = vector("valid_chain");
  assert.equal(v.expect, "accept");

  const chain = load(v.tokens, signerFor(v), { now: v.now });

  assert.equal(chain.tokens.length, 3);
  assert.equal(chain.payloads.length, 3);
  assert.equal(chain.depth, 2);
  assert.equal(chain.delMaxDepth, 7);
  assert.deepEqual(
    chain.payloads.map((p) => p["sub"]),
    ["orchestrator", "summarizer", "formatter"],
  );

  // The leaf, and only the leaf, is what an enforcement point authorizes against:
  // scopes narrowed to {crm.read}, max_rows down to 100, egress none, ttl 300.
  const expected = new Authority({
    scopes: ["crm.read"],
    ceilings: [new EgressRank("none"), new RowLimit(100)],
    ttl: 300,
  });
  assert.equal(canonicalJson(chain.leafAuthority.toWire()), canonicalJson(expected.toWire()));

  // ...and `permits` on the verified chain is the same decision the library
  // would have taken in process, because it is the same relation.
  assert.ok(chain.permits("crm.read", { rows: 100 }).allowed);
  const overRows = chain.permits("crm.read", { rows: 101 });
  assert.equal(overRows.allowed, false);
  assert.deepEqual(
    overRows.reasons.map((r) => r.code),
    [ReasonCode.CEILING_EXCEEDED],
  );
  assert.equal(chain.permits("mail.send").allowed, false); // held by the root, not the leaf
});

test("every adversarial chain is rejected, for exactly the reason it declares", () => {
  for (const name of REJECT_VECTORS) {
    const v = vector(name);
    const expected = v.expect_reject_reason;
    assert.ok(expected, `${name} must declare expect_reject_reason`);
    assert.equal(outcome(v), expected, `${name}: ${v.description}`);
  }
});

test("the declared reasons are the reason codes this build publishes", () => {
  // A vector naming a reason no longer in the vocabulary would otherwise pass
  // the check above by comparing two equal strings that mean nothing.
  const published = new Set<string>(Object.values(WireReasonCode));
  for (const name of REJECT_VECTORS) {
    assert.ok(published.has(vector(name).expect_reject_reason!), name);
  }
  assert.equal(WireReasonCode.EXPIRED, ReasonCode.EXPIRED);
});

test("the alg-confusion guard rejects a token whose header names another algorithm", () => {
  // The header is attacker-controlled, so its `alg` is a claim, never an
  // instruction: the verifier decides which algorithm applies.
  const v = vector("valid_chain");
  const [headerB64, payloadB64, sigB64] = v.tokens[0]!.split(".") as [string, string, string];
  const header = JSON.parse(Buffer.from(headerB64, "base64url").toString("utf8"));
  header["alg"] = "none";
  const forged = Buffer.from(JSON.stringify(header), "utf8").toString("base64url");
  const tokens = [`${forged}.${payloadB64}.${sigB64}`, ...v.tokens.slice(1)];

  assert.equal(outcome({ ...v, tokens }), WireReasonCode.SIGNATURE_INVALID);
});

test("rootKeyIds restricts which key may anchor a chain", () => {
  const v = vector("valid_chain");
  const signer = signerFor(v);

  assert.doesNotThrow(() => load(v.tokens, signer, { now: v.now, rootKeyIds: [v.signer.kid] }));
  assert.throws(
    () => load(v.tokens, signer, { now: v.now, rootKeyIds: ["some-other-root"] }),
    (e: unknown) => e instanceof WireError && e.reason === WireReasonCode.SIGNATURE_INVALID,
  );
});

test("an expired chain and an empty chain are rejected", () => {
  const v = vector("valid_chain");
  // The leaf expires at 300; one second past that, the chain is no longer usable.
  assert.equal(outcome({ ...v, now: 301 }), WireReasonCode.EXPIRED);
  assert.throws(
    () => load([], signerFor(v), { now: v.now }),
    (e: unknown) => e instanceof WireError && e.reason === WireReasonCode.MALFORMED,
  );
});

// ---------------------------------------------------------------------------
// Edge cases the vectors do not cover, because the Python reference is
// ambiguous or unsound on them. Each is pinned here in the fail-closed
// direction; `mint`/`tamper` are the minting side of the wire format, which the
// library itself does not ship — a TypeScript enforcement point verifies chains,
// it does not issue them.
// ---------------------------------------------------------------------------

const VALID = vector("valid_chain");
const VALID_SIGNER = signerFor(VALID);

function payloadText(token: string): string {
  return Buffer.from(token.split(".")[1]!, "base64url").toString("utf8");
}

/** Re-sign `token` over a payload's exact JSON text. */
function mint(token: string, payloadJson: string): string {
  const headerB64 = token.split(".")[0]!;
  const payloadB64 = Buffer.from(payloadJson, "utf8").toString("base64url");
  const sig = VALID_SIGNER.sign(Buffer.from(`${headerB64}.${payloadB64}`, "ascii"));
  return `${headerB64}.${payloadB64}.${sig.toString("base64url")}`;
}

/**
 * Edit one token's payload text, re-sign it, then recompute `par_hash` and
 * re-sign every token below it. Without that repair, editing anything above the
 * leaf changes its signing bytes and the chain is rejected at the byte
 * commitment — correctly, but never reaching the check under test.
 */
function tamper(tokens: string[], index: number, edit: (payload: string) => string): string[] {
  const out = [...tokens];
  out[index] = mint(out[index]!, edit(payloadText(out[index]!)));
  for (let i = index + 1; i < out.length; i++) {
    const parentInput = Buffer.from(out[i - 1]!.split(".").slice(0, 2).join("."), "ascii");
    const payload = JSON.parse(payloadText(out[i]!));
    payload["par_hash"] = createHash("sha256").update(parentInput).digest().toString("base64url");
    out[i] = mint(out[i]!, canonicalJson(payload));
  }
  return out;
}

test("a par_hash that is not base64url is malformed, not a hash mismatch", () => {
  const tokens = tamper(VALID.tokens, 2, (j) =>
    canonicalJson({ ...JSON.parse(j), par_hash: "!!!not-base64!!!" }),
  );
  assert.equal(outcome({ ...VALID, tokens }), WireReasonCode.MALFORMED);
});

test("a non-numeric nbf is refused rather than ignored", () => {
  // Python compares `nbf` to `now` directly and raises a TypeError that escapes
  // `load()` entirely; skipping the check instead would let a token carry a
  // lower time bound nobody enforces. Neither is safe, so it is malformed here.
  const tokens = tamper(VALID.tokens, 2, (j) => canonicalJson({ ...JSON.parse(j), nbf: "soon" }));
  assert.equal(outcome({ ...VALID, tokens }), WireReasonCode.MALFORMED);
});

test("del_max_depth written as a float is not an integer", () => {
  // The two languages disagree about what `7.0` is — a float Python refuses, and
  // in JavaScript simply 7. `parseJson` keeps the literal so the token is judged
  // by what the issuer wrote, and a chain accepted here is accepted there.
  const tokens = tamper(VALID.tokens, 0, (j) =>
    j.replace('"del_max_depth":7', '"del_max_depth":7.0'),
  );
  assert.notDeepEqual(tokens, VALID.tokens);
  assert.equal(outcome({ ...VALID, tokens }), WireReasonCode.DEPTH_INVALID);
});
