/**
 * wire.ts — the Delegation Token: signing backends + offline chain verification.
 *
 * Anchors and delegation tokens are signed over canonical JSON bytes. Two
 * backends ship, matching the Python library's `attenu_guard.wire`:
 *
 *   `HS256TestSigner`  stdlib HMAC-SHA256, for tests, examples and local dev;
 *   `Ed25519Signer`    the production signer the Internet-Draft requires, with
 *                      `Ed25519Verifier` for anyone holding only the public half.
 *
 * The second half of the module is `load()`: the Offline Verification Algorithm
 * of draft-asor-wimse-agent-delegation-chain-01, ported from `wire.py`'s
 * `load()`. A Delegation Token is a compact, JWT-shaped, JWS-signed object
 * carrying one hop's `Authority` plus enough chain-linkage state (`del_depth`,
 * `del_max_depth`, `par_hash`) that an Enforcement Point can verify an entire
 * Delegation Chain with no call to an authorization server. The 17 interop
 * vectors under `test/fixtures/vectors/` are the check on that port: they are
 * generated by the Python reference implementation and each declares the exact
 * reason it must be accepted or rejected for.
 *
 * This module MINTS nothing. Serialization (`serialize`/`serialize_chain` in
 * Python) is the issuing side and lives with whoever holds the signing key;
 * what a TypeScript enforcement point needs is the verifying side.
 *
 * Everything here is built on Node's own `node:crypto`, so the package keeps
 * zero runtime dependencies. Ed25519 keys are wrapped in the fixed DER prefixes
 * below rather than pulled from a library.
 */

import {
  createHash,
  createHmac,
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  sign as cryptoSign,
  timingSafeEqual,
  verify as cryptoVerify,
  type KeyObject,
} from "node:crypto";
import { TextDecoder } from "node:util";

import { Authority } from "./authority.js";
import {
  CanonicalizationError,
  DuplicateMemberError,
  NonFiniteNumberError,
  RawNumber,
  UnsafeIntegerError,
  canonicalJson,
  parseJson,
  toPlain,
  type CJson,
  type Json,
} from "./canonical.js";
import type { Context } from "./ceilings.js";
import { ReasonCode, type Decision } from "./reasons.js";

/**
 * The pluggable signing and verification backend. `alg` is the JOSE algorithm
 * identifier that goes in a token header.
 */
export interface Signer {
  readonly alg: string;
  readonly kid?: string | null;
  sign(signingInput: Buffer): Buffer;
  verify(signingInput: Buffer, sig: Buffer, keyId?: string | null): boolean;
}

/**
 * stdlib HMAC-SHA256 signer — the default for tests, examples and local dev,
 * because it needs no key management at all.
 *
 * NOT FOR PRODUCTION. HMAC is symmetric: `sign` and `verify` use the identical
 * secret, so anyone able to verify a bundle is also able to forge one. That
 * precludes the property the draft is built around — public offline
 * verification at an untrusted enforcement point — because every verifier would
 * have to hold the minting secret. Use `Ed25519Signer` in production; this
 * class exists so the wire format and the interop fixtures can be exercised
 * with no key distribution.
 */
export class HS256TestSigner implements Signer {
  readonly alg = "HS256";
  readonly kid: string;

  constructor(
    private readonly secret: Buffer,
    kid = "test",
  ) {
    this.kid = kid;
  }

  sign(signingInput: Buffer): Buffer {
    return createHmac("sha256", this.secret).update(signingInput).digest();
  }

  verify(signingInput: Buffer, sig: Buffer, _keyId?: string | null): boolean {
    // `keyId` is accepted for parity with multi-key signers but not used for
    // key selection: this signer holds exactly one secret. The comparison is
    // constant-time to avoid a signature-forgery timing oracle.
    const expected = this.sign(signingInput);
    return expected.length === sig.length && timingSafeEqual(expected, sig);
  }
}

// Fixed DER wrappers for raw Ed25519 keys (RFC 8410). A raw 32-byte public key
// becomes a SubjectPublicKeyInfo by prefixing the first; a raw 32-byte private
// key becomes a PKCS#8 PrivateKeyInfo by prefixing the second.
const ED25519_SPKI_PREFIX = Buffer.from("302a300506032b6570032100", "hex");
const ED25519_PKCS8_PREFIX = Buffer.from("302e020100300506032b657004220420", "hex");

function publicKeyFromRaw(raw: Buffer): KeyObject {
  if (raw.length !== 32) {
    throw new Error(`an Ed25519 public key is 32 bytes, got ${raw.length}`);
  }
  return createPublicKey({
    key: Buffer.concat([ED25519_SPKI_PREFIX, raw]),
    format: "der",
    type: "spki",
  });
}

function privateKeyFromRaw(raw: Buffer): KeyObject {
  if (raw.length !== 32) {
    throw new Error(`an Ed25519 private key is 32 bytes, got ${raw.length}`);
  }
  return createPrivateKey({
    key: Buffer.concat([ED25519_PKCS8_PREFIX, raw]),
    format: "der",
    type: "pkcs8",
  });
}

function rawPublicBytes(key: KeyObject): Buffer {
  const der = key.export({ format: "der", type: "spki" });
  return Buffer.from(der.subarray(der.length - 32));
}

function rawPrivateBytes(key: KeyObject): Buffer {
  const der = key.export({ format: "der", type: "pkcs8" });
  return Buffer.from(der.subarray(der.length - 32));
}

/**
 * The production signer the draft requires ("Implementations MUST support
 * Ed25519"); JOSE alg "EdDSA". Public-key, so — unlike `HS256TestSigner` — a
 * verifier never needs the signing secret, which is exactly what offline
 * verification at an untrusted edge depends on.
 */
export class Ed25519Signer implements Signer {
  readonly alg = "EdDSA";
  readonly kid: string;
  private readonly privateKey: KeyObject;
  private readonly publicKey: KeyObject;

  constructor(privateKey?: KeyObject, kid = "ed25519-1") {
    if (privateKey === undefined) {
      const pair = generateKeyPairSync("ed25519");
      this.privateKey = pair.privateKey;
      this.publicKey = pair.publicKey;
    } else {
      this.privateKey = privateKey;
      this.publicKey = createPublicKey(privateKey);
    }
    this.kid = kid;
  }

  /** A signer wrapping a freshly generated keypair. */
  static generate(kid = "ed25519-1"): Ed25519Signer {
    return new Ed25519Signer(undefined, kid);
  }

  /** Rebuild a signer from the 32 raw bytes `privateBytesRaw` produced. */
  static fromPrivateBytes(raw: Buffer, kid = "ed25519-1"): Ed25519Signer {
    return new Ed25519Signer(privateKeyFromRaw(raw), kid);
  }

  sign(signingInput: Buffer): Buffer {
    return cryptoSign(null, signingInput, this.privateKey);
  }

  verify(signingInput: Buffer, sig: Buffer, _keyId?: string | null): boolean {
    try {
      return cryptoVerify(null, signingInput, this.publicKey, sig);
    } catch {
      return false;
    }
  }

  /** The 32-byte raw public key — a trust anchor to distribute out of band. */
  publicBytesRaw(): Buffer {
    return rawPublicBytes(this.publicKey);
  }

  /** The 32-byte raw private key — what a key FILE stores, never a repo. */
  privateBytesRaw(): Buffer {
    return rawPrivateBytes(this.privateKey);
  }
}

/**
 * The public-key-only counterpart of `Ed25519Signer` — what a console, an
 * auditor or an ingest server holds. It verifies anchors signed by the matching
 * private key and can never sign: `sign` throws.
 */
export class Ed25519Verifier implements Signer {
  readonly alg = "EdDSA";
  readonly kid: string;
  private readonly publicKey: KeyObject;

  constructor(publicBytesRaw: Buffer, kid = "ed25519-1") {
    this.publicKey = publicKeyFromRaw(publicBytesRaw);
    this.kid = kid;
  }

  sign(_signingInput: Buffer): Buffer {
    throw new Error("Ed25519Verifier holds no private key and cannot sign");
  }

  verify(signingInput: Buffer, sig: Buffer, _keyId?: string | null): boolean {
    try {
      return cryptoVerify(null, signingInput, this.publicKey, sig);
    } catch {
      return false;
    }
  }

  publicBytesRaw(): Buffer {
    return rawPublicBytes(this.publicKey);
  }
}

// ===========================================================================
// base64url (RFC 7515 §2: standard base64, `+`/`/` -> `-`/`_`, no `=` padding)
// ===========================================================================

/** Encode `data` as unpadded base64url — the encoding every token part uses. */
export function b64urlEncode(data: Buffer): string {
  return data.toString("base64url");
}

const B64URL = /^[A-Za-z0-9_-]*$/;

/**
 * Decode unpadded base64url. Node re-pads internally, so a token part never has
 * to carry `=`.
 *
 * The alphabet and length are checked first, and a bad string throws. Node's own
 * decoder is lenient — it silently drops characters outside the alphabet — which
 * would turn a garbage `par_hash` into a *hash* mismatch instead of the
 * malformed input it actually is. Python's `b64url_decode` raises there and
 * `load()` reports `malformed`; this check is what keeps the two reporting the
 * same reason for the same bytes. A length of 1 mod 4 encodes no whole byte and
 * is rejected for the same reason.
 */
export function b64urlDecode(s: string): Buffer {
  if (!B64URL.test(s) || s.length % 4 === 1) {
    throw new Error(`not valid base64url: ${JSON.stringify(s)}`);
  }
  return Buffer.from(s, "base64url");
}

// ===========================================================================
// Errors / reason codes
// ===========================================================================

/**
 * Wire-verification-specific reason codes, string constants (same pattern as
 * `ReasonCode` — see reasons.ts). `EXPIRED` is not reinvented: it aliases
 * `ReasonCode.EXPIRED` verbatim (identical string, identical meaning: a
 * time-bound invariant failed), covering both "now is past exp" and "exp is not
 * monotonic along the chain" — the draft treats both as the same class of check
 * (verification step 5).
 */
export const WireReasonCode = {
  SIGNATURE_INVALID: "signature_invalid",
  PAR_HASH_MISMATCH: "par_hash_mismatch",
  DEPTH_INVALID: "depth_invalid",
  NOT_NARROWER: "not_narrower",
  MALFORMED: "malformed",
  NON_FINITE: "non_finite",
  DUPLICATE_MEMBER: "duplicate_member",
  NON_CANONICAL: "non_canonical",
  EXPIRED: ReasonCode.EXPIRED, // "expired" — reuse, don't reinvent
} as const;

export type WireReasonCodeValue = (typeof WireReasonCode)[keyof typeof WireReasonCode];

/**
 * Thrown by `load()` on the FIRST verification failure (the draft: "denying on
 * the first failure") — offline chain verification is fail-fast and fail-closed,
 * not an aggregation of every problem found.
 *
 * The constructor takes `(reason, message)`, mirroring Python's `WireError` so
 * the two `load()`s read the same line for line. That is the opposite order to
 * `AuthorityError(message, reason)`; here the reason code is the contract and
 * the message is the human gloss.
 */
export class WireError extends Error {
  readonly reason: string;

  constructor(reason: string, message = "") {
    super(message);
    this.name = "WireError";
    this.reason = reason;
  }
}

// ===========================================================================
// Parsing: compact JWS -> header, payload, signature, signing input
// ===========================================================================

interface ParsedToken {
  header: Record<string, Json>;
  payload: Record<string, Json>;
  /**
   * The payload with number literals still attached. JavaScript has one numeric
   * type, so `3` and `3.0` land on the same value and only the literal says
   * which the issuer wrote — which `del_max_depth` has to be able to tell apart
   * for the few semantic checks that distinguish integer JSON syntax.
   */
  payloadRaw: Record<string, CJson>;
  sig: Buffer;
  /** The exact bytes the signature covers, and what `par_hash` commits to. */
  signingInput: Buffer;
}

function isJsonObject(value: unknown): value is Record<string, Json> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function parseToken(token: string): ParsedToken {
  const parts = token.split(".");
  if (parts.length !== 3) {
    throw new WireError(
      WireReasonCode.MALFORMED,
      `expected 3 dot-separated parts, got ${parts.length}`,
    );
  }
  const [headerB64, payloadB64, sigB64] = parts as [string, string, string];
  let headerBytes: Buffer;
  let payloadBytes: Buffer;
  let sig: Buffer;
  try {
    headerBytes = b64urlDecode(headerB64);
    payloadBytes = b64urlDecode(payloadB64);
    sig = b64urlDecode(sigB64);
  } catch (e) {
    throw new WireError(WireReasonCode.MALFORMED, `could not decode token: ${String(e)}`);
  }

  let headerRaw: CJson;
  let payloadRaw: CJson;
  try {
    const decoder = new TextDecoder("utf-8", { fatal: true });
    headerRaw = parseJson(decoder.decode(headerBytes));
    payloadRaw = parseJson(decoder.decode(payloadBytes));
  } catch (e) {
    if (e instanceof DuplicateMemberError) {
      throw new WireError(WireReasonCode.DUPLICATE_MEMBER, e.message);
    }
    if (e instanceof NonFiniteNumberError) {
      throw new WireError(WireReasonCode.NON_FINITE, e.message);
    }
    if (e instanceof CanonicalizationError) {
      throw new WireError(WireReasonCode.NON_CANONICAL, e.message);
    }
    throw new WireError(WireReasonCode.MALFORMED, `could not parse token JSON: ${String(e)}`);
  }

  const header = toPlain<Json>(headerRaw);
  const payload = toPlain<Json>(payloadRaw);
  if (!isJsonObject(header) || !isJsonObject(payload)) {
    throw new WireError(WireReasonCode.MALFORMED, "header/payload must be JSON objects");
  }
  let canonicalHeader: string;
  let canonicalPayload: string;
  try {
    canonicalHeader = canonicalJson(headerRaw);
    canonicalPayload = canonicalJson(payloadRaw);
  } catch (e) {
    if (e instanceof NonFiniteNumberError) {
      throw new WireError(WireReasonCode.NON_FINITE, e.message);
    }
    // Mirrors non-finite handling above: an integer past the safe binary64
    // range is a malformed claim, not merely a non-canonical byte form — it
    // cannot be represented at all, safely, so it is rejected before
    // verification rather than compared byte-for-byte.
    if (e instanceof UnsafeIntegerError) {
      throw new WireError(WireReasonCode.MALFORMED, e.message);
    }
    if (e instanceof CanonicalizationError) {
      throw new WireError(WireReasonCode.NON_CANONICAL, e.message);
    }
    throw e;
  }
  if (
    !headerBytes.equals(Buffer.from(canonicalHeader, "utf8")) ||
    !payloadBytes.equals(Buffer.from(canonicalPayload, "utf8"))
  ) {
    throw new WireError(
      WireReasonCode.NON_CANONICAL,
      "token header and payload must be RFC 8785 JCS bytes",
    );
  }
  return {
    header,
    payload,
    payloadRaw: payloadRaw as Record<string, CJson>,
    sig,
    // ASCII, not utf8: the signing input is by definition the two base64url
    // parts and a dot, so any byte outside ASCII could not have decoded.
    signingInput: Buffer.from(`${headerB64}.${payloadB64}`, "ascii"),
  };
}

/**
 * Rebuild the FULL `Authority` a token carries, including `ttl` (recovered as
 * `exp - iat`), so `load()` can hand the very same `Authority.isNarrowerThan`
 * the library uses for in-process attenuation. The draft's subsumption relation
 * and the library relation must be the same relation, so this reconstitutes an
 * `Authority` rather than comparing claim shapes by hand.
 *
 * `ttl` is deliberately absent from `authorization_details` on the wire: token
 * lifetime is carried once, at the top level, in the standard `iat`/`exp`
 * claims, where it cannot drift out of sync with itself.
 */
function authorityFromPayload(payload: Record<string, Json>): Authority {
  const details = payload["authorization_details"];
  if (!Array.isArray(details) || details.length === 0) {
    throw new WireError(WireReasonCode.MALFORMED, "authorization_details missing or empty");
  }
  const d0 = details[0];
  if (!isJsonObject(d0) || d0["type"] !== "agent_delegation") {
    throw new WireError(
      WireReasonCode.MALFORMED,
      "authorization_details[0].type must be 'agent_delegation'",
    );
  }
  const iat = payload["iat"];
  const exp = payload["exp"];
  if (typeof iat !== "number" || typeof exp !== "number") {
    throw new WireError(WireReasonCode.MALFORMED, "iat/exp missing or not numeric");
  }
  const wire = {
    scopes: d0["scopes"] ?? [],
    constraints: d0["constraints"] ?? [],
    ttl: exp - iat,
  };
  try {
    return Authority.fromWire(wire as CJson);
  } catch (e) {
    // A malformed constraint shape, and anything else the ceiling registry
    // refuses to build: the token is unusable, so fail closed.
    throw new WireError(WireReasonCode.MALFORMED, `invalid authorization_details: ${String(e)}`);
  }
}

// ===========================================================================
// load() — the Offline Verification Algorithm
// ===========================================================================

/**
 * A chain that passed every check in `load()`. It carries only what an
 * Enforcement Point needs afterwards: the LEAF authority — the only authority
 * ever checked against an attempted action — plus enough raw material to log
 * and debug with.
 */
export class VerifiedChain {
  constructor(
    readonly tokens: readonly string[],
    readonly payloads: readonly Record<string, Json>[],
    readonly leafAuthority: Authority,
    readonly depth: number,
    readonly delMaxDepth: number,
  ) {}

  /**
   * Authorize `scope` (with request context `ctx`) against the LEAF authority.
   * Delegates entirely to `Authority.permits`; no policy logic is reimplemented
   * here, so a decision taken from a verified chain and a decision taken
   * in-process are the same decision.
   */
  permits(scope: string, ctx: Context | null = null): Decision {
    return this.leafAuthority.permits(scope, ctx);
  }
}

export interface LoadOptions {
  /**
   * If given, restricts which `kid` the ROOT token (DT_0) may present — "DT_0
   * MUST verify under a trusted root key". Tokens deeper in the chain are not
   * restricted this way: the root is the trust anchor, and every hop below it
   * is bound to the root by `par_hash`.
   */
  rootKeyIds?: Iterable<string | null> | null;
  /**
   * Epoch seconds to evaluate the time claims at. Defaults to 0, never to a
   * real clock, so vectors and fixtures stay byte-for-byte reproducible — pass
   * `Math.floor(Date.now() / 1000)` when verifying a live token.
   */
  now?: number;
}

/**
 * Run the Offline Verification Algorithm over `tokens` (`[DT_0, ..., DT_n]`,
 * root-first) and, on success, return a `VerifiedChain`. Denies on the FIRST
 * failure by throwing a `WireError` whose `.reason` is one of the
 * `WireReasonCode` constants.
 *
 * `signer` verifies every token in the chain — this implementation's
 * simplifying trust model, matching Python's, is ONE signer/key material per
 * whole chain. A production multi-issuer deployment would generalize `signer`
 * into a `kid`-keyed resolver, which is a straightforward extension left out
 * here.
 *
 * Steps performed, in the draft's own order:
 *   1. JWS signature of every DT_i (+ the alg-confusion guard: the header's
 *      declared `alg` must equal `signer.alg` — never trust a token's own claim
 *      about which algorithm verifies it), plus the optional `rootKeyIds`
 *      restriction on DT_0.
 *   2. The `par_hash` byte-commitment for every i > 0, compared in constant
 *      time; DT_0 MUST NOT carry one.
 *   3. `del_depth`/`del_max_depth` bounds.
 *   4. Subsumption: DT_i's authority `isNarrowerThan` DT_{i-1}'s for every
 *      i > 0 — REUSES the core's own relation (authority.ts); not
 *      reimplemented here.
 *   5. Time: `now <= exp` (and `now >= nbf` where present) for every DT_i, and
 *      `exp` non-increasing along the chain.
 *
 * OUT OF SCOPE, as in the Python reference implementation — documented here
 * rather than silently skipped: step 6 (`cnf`/DPoP holder-binding proof) and
 * step 7 (Token Status List revocation). Neither is checked.
 */
export function load(
  tokens: readonly string[],
  signer: Signer,
  options: LoadOptions = {},
): VerifiedChain {
  const { rootKeyIds = null, now = 0 } = options;
  if (tokens.length === 0) {
    throw new WireError(WireReasonCode.MALFORMED, "empty token chain");
  }

  const parsed = tokens.map((t) => parseToken(t));

  // ---- step 1: signatures -------------------------------------------------
  const trustedRoots = rootKeyIds === null ? null : new Set(rootKeyIds);
  for (let i = 0; i < parsed.length; i++) {
    const { header, sig, signingInput } = parsed[i]!;
    const alg = header["alg"];
    if (alg !== signer.alg) {
      throw new WireError(
        WireReasonCode.SIGNATURE_INVALID,
        `token[${i}] header alg ${JSON.stringify(alg)} != signer alg ${JSON.stringify(signer.alg)}`,
      );
    }
    const kid = typeof header["kid"] === "string" ? header["kid"] : null;
    if (i === 0 && trustedRoots !== null && !trustedRoots.has(kid)) {
      throw new WireError(
        WireReasonCode.SIGNATURE_INVALID,
        `root token kid ${JSON.stringify(kid)} not in trusted rootKeyIds`,
      );
    }
    if (!signer.verify(signingInput, sig, kid)) {
      throw new WireError(
        WireReasonCode.SIGNATURE_INVALID,
        `token[${i}] signature does not verify`,
      );
    }
  }

  // ---- step 2: par_hash byte-commitment (constant-time, over hex) ---------
  // The commitment is over the PARENT's signing input — its exact serialized
  // bytes — which is what makes a spliced chain detectable even when the
  // substituted parent is broad enough that subsumption alone would pass it.
  if ("par_hash" in parsed[0]!.payload) {
    throw new WireError(WireReasonCode.MALFORMED, "DT_0 (del_depth 0) MUST NOT carry par_hash");
  }
  for (let i = 1; i < parsed.length; i++) {
    const expectedHex = createHash("sha256").update(parsed[i - 1]!.signingInput).digest("hex");
    const gotB64 = parsed[i]!.payload["par_hash"];
    if (typeof gotB64 !== "string") {
      throw new WireError(WireReasonCode.PAR_HASH_MISMATCH, `token[${i}] missing par_hash`);
    }
    let gotHex: string;
    try {
      gotHex = b64urlDecode(gotB64).toString("hex");
    } catch (e) {
      throw new WireError(
        WireReasonCode.MALFORMED,
        `token[${i}] par_hash is not valid base64url: ${String(e)}`,
      );
    }
    if (!constantTimeEqualAscii(expectedHex, gotHex)) {
      throw new WireError(
        WireReasonCode.PAR_HASH_MISMATCH,
        `token[${i}] par_hash does not match parent token[${i - 1}]'s signing input ` +
          "(splice, wrong parent, or tampered parent)",
      );
    }
  }

  // ---- step 3: del_depth / del_max_depth ----------------------------------
  const rootPayload = parsed[0]!.payload;
  if (rootPayload["del_depth"] !== 0) {
    throw new WireError(WireReasonCode.DEPTH_INVALID, "DT_0.del_depth must be 0");
  }
  const delMaxDepth = rootPayload["del_max_depth"];
  if (
    typeof delMaxDepth !== "number" ||
    !isIntegerLiteral(parsed[0]!.payloadRaw["del_max_depth"]) ||
    delMaxDepth <= 0
  ) {
    throw new WireError(
      WireReasonCode.DEPTH_INVALID,
      "DT_0.del_max_depth must be a positive integer",
    );
  }
  // `del_max_depth` is the maximum chain LENGTH (a token count) while
  // `del_depth` is a 0-based index, so the leaf's index must be strictly below
  // it — a 3-token chain has a leaf at del_depth 2 and needs del_max_depth >= 3.
  const n = parsed.length - 1;
  if (!(n < delMaxDepth)) {
    throw new WireError(
      WireReasonCode.DEPTH_INVALID,
      `chain length ${n + 1} exceeds del_max_depth ${delMaxDepth} ` +
        `(need leaf del_depth ${n} < del_max_depth)`,
    );
  }
  for (let i = 0; i < parsed.length; i++) {
    if (parsed[i]!.payload["del_depth"] !== i) {
      throw new WireError(
        WireReasonCode.DEPTH_INVALID,
        `token[${i}].del_depth = ${JSON.stringify(parsed[i]!.payload["del_depth"])}, expected ${i}`,
      );
    }
  }

  // ---- step 4: subsumption (reuse Authority.isNarrowerThan) ---------------
  const authorities = parsed.map((p) => authorityFromPayload(p.payload));
  for (let i = 1; i < authorities.length; i++) {
    if (!authorities[i]!.isNarrowerThan(authorities[i - 1]!)) {
      throw new WireError(
        WireReasonCode.NOT_NARROWER,
        `token[${i}] authority is not narrower than token[${i - 1}]'s ` +
          "(widened scope, loosened/dropped ceiling, or looser ttl)",
      );
    }
  }

  // ---- step 5: time -------------------------------------------------------
  let prevExp: number | null = null;
  for (let i = 0; i < parsed.length; i++) {
    const payload = parsed[i]!.payload;
    const exp = payload["exp"];
    if (typeof exp !== "number") {
      throw new WireError(WireReasonCode.MALFORMED, `token[${i}] missing numeric exp`);
    }
    // `nbf` is optional; absent or null means "no lower bound". Anything else
    // that is not a number is refused rather than ignored — Python compares it
    // to `now` directly and raises a TypeError that escapes `load()`, so a
    // caller catching only `WireError` would see the chain neither accepted nor
    // cleanly rejected. Failing closed here is the safe reading of both.
    const nbf = payload["nbf"];
    if (nbf !== undefined && nbf !== null) {
      if (typeof nbf !== "number") {
        throw new WireError(WireReasonCode.MALFORMED, `token[${i}] nbf is not numeric`);
      }
      if (now < nbf) {
        throw new WireError(
          WireReasonCode.EXPIRED,
          `token[${i}] not yet valid: now=${now} < nbf=${nbf}`,
        );
      }
    }
    if (now > exp) {
      throw new WireError(WireReasonCode.EXPIRED, `token[${i}] expired: now=${now} > exp=${exp}`);
    }
    if (prevExp !== null && exp > prevExp) {
      throw new WireError(
        WireReasonCode.EXPIRED,
        `token[${i}] exp=${exp} exceeds parent token[${i - 1}] exp=${prevExp} ` +
          "(exp must be monotonic non-increasing along the chain)",
      );
    }
    prevExp = exp;
  }

  // ---- steps 6-7: OUT OF SCOPE (see the doc comment) ----------------------
  //   step 6: cnf/DPoP holder-binding proof — not checked.
  //   step 7: Token Status List revocation — not checked.

  return new VerifiedChain(
    [...tokens],
    parsed.map((p) => p.payload),
    authorities[authorities.length - 1]!,
    parsed[parsed.length - 1]!.payload["del_depth"] as number,
    delMaxDepth,
  );
}

/**
 * Did the issuer write an integer, as opposed to a value that merely equals one?
 * `parseJson` keeps every number's original literal precisely so this question
 * can still be asked after parsing.
 */
function isIntegerLiteral(value: CJson | undefined): boolean {
  if (value instanceof RawNumber) return /^-?\d+$/.test(value.raw);
  return typeof value === "number" && Number.isInteger(value);
}

/**
 * Compare two ASCII strings without an early exit, so a near-miss and a wild
 * miss take the same time. `timingSafeEqual` throws on unequal lengths, so the
 * length is checked first — that leak is only the digest length, which is fixed
 * and public anyway.
 */
function constantTimeEqualAscii(a: string, b: string): boolean {
  const ab = Buffer.from(a, "ascii");
  const bb = Buffer.from(b, "ascii");
  return ab.length === bb.length && timingSafeEqual(ab, bb);
}
